language: rust
rust: nightly
addons:
  apt:
    packages:
      - libdbus-1-dev
      - libssl-dev
cache:
  directories:
    - /home/travis/.cargo/
before_cache:
  - rm -rf /home/travis/.cargo/registry
