[package]
name = "icie"
version = "0.5.0"
authors = ["Mateusz Cegiełka <mateusz@cegla.net>"]
edition = "2018"

[dependencies]
ci = { path = "../ci" }
evscode = { path = "../evscode" }
json = "0.11"
lazy_static = "1.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellexpand = "1.0"
