[package]
name = "icie"
version = "0.5.0"
authors = ["Mateusz Cegiełka <mateusz@cegla.net>"]
edition = "2018"

[dependencies]
ci = { path = "../ci" }
dirs = "1.0"
evscode = { path = "../evscode" }
failure = "0.1.5"
json = "0.11"
keyring = "0.7"
lazy_static = "1.0"
log = "0.4"
rand = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellexpand = "1.0"
unijudge = { git = "https://github.com/matcegla/unijudge" }
