[package]
name = "icie"
version = "0.5.4"
authors = ["Mateusz Cegiełka <mateusz@cegla.net>"]
edition = "2018"

[dependencies]
dirs = "1.0"
evscode = { git = "https://github.com/pustaczek/evscode" }
itertools = "0.8"
json = "0.11"
keyring = "0.7"
lazy_static = "1.0"
log = "0.4"
rand = "0.6"
regex = "1.1"
reqwest = { version = "0.9.14", default-features = false, features = ["rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellexpand = "1.0"
unijudge = { git = "https://github.com/pustaczek/unijudge" }
wait-timeout = "0.2"
walkdir = "2.2"
