[package]
name = "unijudge"
version = "0.1.0"
authors = ["Mateusz Cegiełka <mateusz@cegla.net>"]
edition = "2018"

[dependencies]
backtrace = "0.3"
debris = { git = "https://github.com/pustaczek/debris" }
log = "0.4"
reqwest = { version = "0.9.14", default-features = false }
serde = "1.0"
serde_json = "1.0"
